import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function Dashboard({ telemetry, profile, onBack }) {
    const { currentPS, maxPS, speedKmh, hasPermission, requestPermissions, isCalibrating } = telemetry;
    if (hasPermission === null) {
        return (_jsxs("div", { className: "glass-panel w-full max-w-sm p-6 flex flex-col items-center gap-4 text-center", children: [_jsx("h2", { className: "text-xl font-bold", children: "Permissions Required" }), _jsx("p", { className: "text-sm text-gray-400", children: "We need access to your device's motion and orientation sensors to calculate acceleration." }), _jsx("button", { onClick: requestPermissions, className: "mt-4 bg-[var(--color-neon-blue)] text-black font-bold py-3 px-6 rounded-lg w-full", children: "Grant Access" })] }));
    }
    if (isCalibrating) {
        return (_jsxs("div", { className: "glass-panel w-full max-w-sm p-8 flex flex-col items-center justify-center gap-6 text-center", children: [_jsx("div", { className: "animate-spin rounded-full h-16 w-16 border-t-4 border-[var(--color-neon-blue)] border-solid" }), _jsxs("div", { children: [_jsx("h2", { className: "text-xl font-bold text-glow text-[var(--color-neon-blue)]", children: "Calibrating..." }), _jsx("p", { className: "text-sm text-gray-400 mt-2", children: "Please keep your phone completely still in the mount." })] })] }));
    }
    return (_jsxs("div", { className: "w-full flex flex-col items-center justify-center gap-8", children: [_jsxs("div", { className: "relative w-64 h-64 flex items-center justify-center rounded-full glass-panel border-[var(--color-neon-blue)] border-opacity-30 border-[3px] shadow-[0_0_30px_rgba(0,243,255,0.15)]", children: [_jsx("div", { className: "absolute top-8 text-gray-400 text-sm font-bold tracking-widest", children: "WHEEL HP" }), _jsxs("div", { className: "flex flex-col items-center justify-center mt-4", children: [_jsx("span", { className: "text-6xl font-mono font-bold text-glow text-[var(--color-neon-blue)]", children: Math.round(currentPS) }), _jsx("span", { className: "text-lg font-bold text-[var(--color-neon-blue)] opacity-80 mt-1", children: "PS" })] })] }), _jsxs("div", { className: "flex w-full max-w-sm gap-4", children: [_jsxs("div", { className: "flex-1 glass-panel p-4 flex flex-col items-center justify-center", children: [_jsx("span", { className: "text-3xl font-mono font-bold text-white tracking-tighter", children: Math.round(speedKmh) }), _jsx("span", { className: "text-xs text-gray-400 uppercase tracking-widest mt-1", children: "km/h" })] }), _jsxs("div", { className: "flex-1 glass-panel p-4 flex flex-col items-center justify-center", children: [_jsx("span", { className: "text-3xl font-mono font-bold text-[#ff0055] text-glow tracking-tighter", children: Math.round(maxPS) }), _jsx("span", { className: "text-xs text-[#ff0055] uppercase tracking-widest mt-1", children: "Peak PS" })] })] }), _jsx("button", { className: "mt-4 border-2 border-zinc-700 hover:border-zinc-500 text-gray-300 font-bold py-3 px-8 rounded-full active:scale-95 transition-all text-sm tracking-widest", onClick: onBack, children: "END SESSION" })] }));
}
